In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
import re

## Set up
1. Load parquet file
2. Combine title + summary 
3. Clean text (lowercase, remove punctuation, etc.)

In [2]:
doc_path = '../data/download_sf_dataset.parquet'
df_sf_dataset = pd.read_parquet(doc_path)
print(f"shape: {df_sf_dataset.shape}")
print(f"first few rows: {df_sf_dataset.head(5)}")
print(f"columns: {df_sf_dataset.columns}")

shape: (114115, 7)
first few rows:                                      id                              story_id  \
0  ddfc792e-f757-3cf7-978b-defdd6709c64  d43f6fbc-35b7-45d1-82c7-852413701515
1  e0768f55-4c3e-3f81-87c9-b2d81e980e0f  43e6558d-42bd-4562-bc33-fcc42175e5da
2  59e27515-36c2-3bce-9051-57e841b62f97  576eb652-3db1-4efe-9a60-726392e57965
3  ea224531-6be4-3f83-ab80-b5817b7716ff  dcd9ec38-ebad-4c1a-838b-e467912d185f
4  a4a6294b-76ae-3418-a917-c6011b36101f  0e36ef0c-44a6-4e51-8f21-5e7936528806

                                               title  \
0  Blockchain Stocks To Consider #8212; December ...
1  Adobe AI Pirated Book Suit Adds Pressure to Co...
2  Intrepid Financial Planning Group files SEC Fo...
3                                Extra! Extra! 10/19
4  Trump promises to deploy troops to SF: 'We're ...

                                             summary      wiki_title  \
0  December 20th, 2025 (The Markets Daily - Deliv...  Salesforce.com
1  Adobe has become the latest technology heavywe...  Salesforce.com
2  INSTITUTIONAL HOLDINGS REPORT\n\nIntrepid Fina...  Salesforce.com
3  Hi, all, and happy Sunday! And a great day it ...  Salesforce.com
4  President Donald Trump reiterated his intentio...  Salesforce.com

  sentiment_decision  sentiment_positive
0            neutral            0.284962
1            neutral            0.027630
2            neutral            0.050394
3            neutral            0.062080
4            neutral            0.446811
columns: Index(['id', 'story_id', 'title', 'summary', 'wiki_title',
       'sentiment_decision', 'sentiment_positive'],
      dtype='object')

In [6]:
df_sf_dataset['title'].isnull().sum()

np.int64(0)

In [7]:
df_sf_dataset['summary'].isnull().sum()

np.int64(0)

In [4]:
df_sf_dataset['text'] = df_sf_dataset['title'] + ' ' + df_sf_dataset['summary'] 
df_sf_dataset

,id,story_id,title,summary,wiki_title,sentiment_decision,sentiment_positive,text
0,ddfc792e-f757-3cf7-978b-defdd6709c64,d43f6fbc-35b7-45d1-82c7-852413701515,Blockchain Stocks To Consider #8212; December ...,"December 20th, 2025 (The Markets Daily - Deliv...",Salesforce.com,neutral,0.284962,Blockchain Stocks To Consider #8212; December ...
1,e0768f55-4c3e-3f81-87c9-b2d81e980e0f,43e6558d-42bd-4562-bc33-fcc42175e5da,Adobe AI Pirated Book Suit Adds Pressure to Co...,Adobe has become the latest technology heavywe...,Salesforce.com,neutral,0.027630,Adobe AI Pirated Book Suit Adds Pressure to Co...
2,59e27515-36c2-3bce-9051-57e841b62f97,576eb652-3db1-4efe-9a60-726392e57965,Intrepid Financial Planning Group files SEC Fo...,INSTITUTIONAL HOLDINGS REPORT\n\nIntrepid Fina...,Salesforce.com,neutral,0.050394,Intrepid Financial Planning Group files SEC Fo...
3,ea224531-6be4-3f83-ab80-b5817b7716ff,dcd9ec38-ebad-4c1a-838b-e467912d185f,Extra! Extra! 10/19,"Hi, all, and happy Sunday! And a great day it ...",Salesforce.com,neutral,0.062080,"Extra! Extra! 10/19 Hi, all, and happy Sunday!..."
4,a4a6294b-76ae-3418-a917-c6011b36101f,0e36ef0c-44a6-4e51-8f21-5e7936528806,Trump promises to deploy troops to SF: 'We're ...,President Donald Trump reiterated his intentio...,Salesforce.com,neutral,0.446811,Trump promises to deploy troops to SF: 'We're ...
...,...,...,...,...,...,...,...,...
114110,0d58e322-3801-35dd-a05a-91869d887cd9,a01cfa25-537f-4a93-8ee2-4cbef4765edb,Insider Selling: Salesforce (NYSE:CRM) Insider...,Salesforce Inc. insider Parker Harris sold 13...,Salesforce.com,positive,0.803504,Insider Selling: Salesforce (NYSE:CRM) Insider...
114111,d72f9a78-c1b1-3e0c-9d52-43e2824f2738,35a6c509-4ca9-437b-ab60-863a5719bd62,First row of glory! Xinzhuang Deputy City Anch...,"Xinbei Xinzhuang Vice-President, is growing at...",Salesforce.com,positive,0.828425,First row of glory! Xinzhuang Deputy City Anch...
114112,ef9f5456-dbb4-3ee3-bc8b-655e97785158,a67fc0f5-d364-4dba-af40-248460175554,Benchmarking CCC Intelligent Solutions Holding...,NYSE STOCK REPORT\n\nThis comparative analysis...,Salesforce.com,positive,0.910142,Benchmarking CCC Intelligent Solutions Holding...
114113,78e7fff1-01b4-3376-a6ff-aa39670dde03,90855ad2-5894-4590-b1cd-ec02901e5b03,Kalleon Solutions and Insurance generals Serbi...,With the implementation of the SalesForce Plat...,Salesforce.com,positive,0.920999,Kalleon Solutions and Insurance generals Serbi...
114114,3903195e-bec6-31b5-ac18-92708bb21a38,ee21f552-eac7-49cc-845f-3a6d9039da7e,Annis Gardner Whiting Capital Advisors files S...,INSTITUTIONAL HOLDINGS REPORT\n\nAnnis Gardner...,Salesforce.com,neutral,0.000000,Annis Gardner Whiting Capital Advisors files S...

In [9]:
#remove punctuation, lower case and numbers
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

In [11]:
df_sf_dataset['cleaned_text'] = df_sf_dataset['text'].apply(clean_text)
df_sf_dataset

,id,story_id,title,summary,wiki_title,sentiment_decision,sentiment_positive,text,cleaned_text
0,ddfc792e-f757-3cf7-978b-defdd6709c64,d43f6fbc-35b7-45d1-82c7-852413701515,Blockchain Stocks To Consider #8212; December ...,"December 20th, 2025 (The Markets Daily - Deliv...",Salesforce.com,neutral,0.284962,Blockchain Stocks To Consider #8212; December ...,blockchain stocks to consider december st dec...
1,e0768f55-4c3e-3f81-87c9-b2d81e980e0f,43e6558d-42bd-4562-bc33-fcc42175e5da,Adobe AI Pirated Book Suit Adds Pressure to Co...,Adobe has become the latest technology heavywe...,Salesforce.com,neutral,0.027630,Adobe AI Pirated Book Suit Adds Pressure to Co...,adobe ai pirated book suit adds pressure to co...
2,59e27515-36c2-3bce-9051-57e841b62f97,576eb652-3db1-4efe-9a60-726392e57965,Intrepid Financial Planning Group files SEC Fo...,INSTITUTIONAL HOLDINGS REPORT\n\nIntrepid Fina...,Salesforce.com,neutral,0.050394,Intrepid Financial Planning Group files SEC Fo...,intrepid financial planning group files sec fo...
3,ea224531-6be4-3f83-ab80-b5817b7716ff,dcd9ec38-ebad-4c1a-838b-e467912d185f,Extra! Extra! 10/19,"Hi, all, and happy Sunday! And a great day it ...",Salesforce.com,neutral,0.062080,"Extra! Extra! 10/19 Hi, all, and happy Sunday!...",extra extra hi all and happy sunday and a gre...
4,a4a6294b-76ae-3418-a917-c6011b36101f,0e36ef0c-44a6-4e51-8f21-5e7936528806,Trump promises to deploy troops to SF: 'We're ...,President Donald Trump reiterated his intentio...,Salesforce.com,neutral,0.446811,Trump promises to deploy troops to SF: 'We're ...,trump promises to deploy troops to sf were goi...
...,...,...,...,...,...,...,...,...,...
114110,0d58e322-3801-35dd-a05a-91869d887cd9,a01cfa25-537f-4a93-8ee2-4cbef4765edb,Insider Selling: Salesforce (NYSE:CRM) Insider...,Salesforce Inc. insider Parker Harris sold 13...,Salesforce.com,positive,0.803504,Insider Selling: Salesforce (NYSE:CRM) Insider...,insider selling salesforce nysecrm insider sel...
114111,d72f9a78-c1b1-3e0c-9d52-43e2824f2738,35a6c509-4ca9-437b-ab60-863a5719bd62,First row of glory! Xinzhuang Deputy City Anch...,"Xinbei Xinzhuang Vice-President, is growing at...",Salesforce.com,positive,0.828425,First row of glory! Xinzhuang Deputy City Anch...,first row of glory xinzhuang deputy city ancho...
114112,ef9f5456-dbb4-3ee3-bc8b-655e97785158,a67fc0f5-d364-4dba-af40-248460175554,Benchmarking CCC Intelligent Solutions Holding...,NYSE STOCK REPORT\n\nThis comparative analysis...,Salesforce.com,positive,0.910142,Benchmarking CCC Intelligent Solutions Holding...,benchmarking ccc intelligent solutions holding...
114113,78e7fff1-01b4-3376-a6ff-aa39670dde03,90855ad2-5894-4590-b1cd-ec02901e5b03,Kalleon Solutions and Insurance generals Serbi...,With the implementation of the SalesForce Plat...,Salesforce.com,positive,0.920999,Kalleon Solutions and Insurance generals Serbi...,kalleon solutions and insurance generals serbi...
114114,3903195e-bec6-31b5-ac18-92708bb21a38,ee21f552-eac7-49cc-845f-3a6d9039da7e,Annis Gardner Whiting Capital Advisors files S...,INSTITUTIONAL HOLDINGS REPORT\n\nAnnis Gardner...,Salesforce.com,neutral,0.000000,Annis Gardner Whiting Capital Advisors files S...,annis gardner whiting capital advisors files s...

## EXPLORE TARGETS
4. Run df['sentiment_positive'].describe()
5. Run df['sentiment_decision'].value_counts()
6. Decide thresholds to derive sentiment_decision from sentiment_positive

In [12]:
df_sf_dataset['sentiment_positive'].describe()

count    114115.000000
mean          0.438211
std           0.300181
min           0.000000
25%           0.170771
50%           0.369678
75%           0.741430
max           0.964544
Name: sentiment_positive, dtype: float64

In [13]:
df_sf_dataset['sentiment_decision'].value_counts()

sentiment_decision
neutral     62936
positive    48126
negative     3053
Name: count, dtype: Int64

In [14]:
df_sf_dataset.groupby('sentiment_decision')['sentiment_positive'].describe()

,count,mean,std,min,25%,50%,75%,max
sentiment_decision,,,,,,,,
negative,3053.0,0.082929,0.081008,0.005424,0.023794,0.049750,0.120743,0.423194
neutral,62936.0,0.217928,0.134421,0.000000,0.097005,0.213848,0.363747,0.490537
positive,48126.0,0.748822,0.147218,0.347957,0.627180,0.789772,0.875067,0.964544

In [ ]:
def get_sentiment_label(score):
    if score < 0.2:
        sentiment_decision = 'negative'      # negative
    elif score < 0.5:
        sentiment_decision = 'neutral'
    else:
        sentiment_decision = 'positive'
    return sentiment_decision

## PREPARE DATA
7. Set X = df['text'], y = df['sentiment_positive']
8. Train/test split

### §MODEL PIPELINES
9.  TF-IDF  → raw strings → TfidfVectorizer → regression model
10. Word2Vec → token lists → average word vectors → regression model
11. BERT    → raw strings → BertTokenizer → fine-tune or feature extract

### EVALUATE
12. For each model: predict sentiment_positive score
13. Apply thresholds to derive predicted sentiment_decision label
14. Compare models using MAE/RMSE (score) and accuracy/F1 (label)